
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author doğukan
 */
public class Main extends javax.swing.JFrame {
 private   Queue<String> queue = new LinkedList<String>();
 private   Queue<String> a = new LinkedList<String>();
 private   Queue<String> b = new LinkedList<String>();
 private   Queue<String> c = new LinkedList<String>();
 private   Queue<String> d = new LinkedList<String>();
  private   ArrayList<String> answers = new ArrayList<String>();
int i=0;

   
 
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        try(Scanner scanner=new Scanner(new BufferedReader(new FileReader("Sorular.txt")))){
        while(scanner.hasNext()){
            String s=scanner.nextLine();
            queue.offer(s);
        }
         a.offer("CORBA");  b.offer("MANTI"); c.offer("MENEMEN"); d.offer("MUHALLEBI");
           a.offer("ASK");  b.offer("SEFKAT"); c.offer("GUVEN"); d.offer("SABIR");
        a.offer("7.5");  b.offer("6.5"); c.offer("5.5"); d.offer("8.5");
          a.offer("39");  b.offer("49"); c.offer("59"); d.offer("69");
            a.offer("SIS BOMBASI");  b.offer("BAKIR IGNE"); c.offer("SU BALONU"); d.offer("SEMSİYE");
             a.offer("ELMA");  b.offer("NAR"); c.offer("DUT"); d.offer("UZUM");
            a.offer("DUMUL");  b.offer("FODUL"); c.offer("TIRIT"); d.offer("KADIT");
              
        answers.add("CORBA");  answers.add("ASK");   answers.add("5.5");  answers.add("69"); answers.add("BAKIR IGNE"); answers.add("NAR"); answers.add("KADIT");
              
            al();
            
            
    } catch (FileNotFoundException ex) {
         Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        soru = new javax.swing.JLabel();
        A = new javax.swing.JButton();
        B = new javax.swing.JButton();
        C = new javax.swing.JButton();
        D = new javax.swing.JButton();
        mesaj = new javax.swing.JLabel();
        dogru = new javax.swing.JLabel();
        alti = new javax.swing.JLabel();
        dort = new javax.swing.JLabel();
        uc = new javax.swing.JLabel();
        iki = new javax.swing.JLabel();
        bir = new javax.swing.JLabel();
        bes = new javax.swing.JLabel();
        yedi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        joker1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cekil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        soru.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        A.setText("jButton1");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        B.setText("jButton2");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        C.setText("jButton3");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        D.setText("jButton4");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        mesaj.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        mesaj.setForeground(new java.awt.Color(255, 0, 0));

        dogru.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        dogru.setForeground(new java.awt.Color(0, 204, 51));

        alti.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        alti.setText("15000 TL");

        dort.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        dort.setText("3000 TL");

        uc.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        uc.setText("2000 TL");

        iki.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        iki.setText("1000 TL");

        bir.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bir.setText("500 TL");

        bes.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bes.setText(" 7500 TL");

        yedi.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        yedi.setText("30000 TL");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("C)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("B)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("D)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("A)");

        joker1.setText("%50");
        joker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joker1ActionPerformed(evt);
            }
        });

        jButton1.setText("Seyirci");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cekil.setText("Çekil");
        cekil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(soru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alti)
                            .addComponent(yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dogru, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(uc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dort, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(joker1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(cekil, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iki, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(soru, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(alti, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addComponent(dort, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(uc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(iki, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(bir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(joker1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cekil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dogru, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
void ekle(){
    
     try {
         AudioInputStream stream=AudioSystem.getAudioInputStream(new File("bildin.wav"));
         try {
             Clip clip=AudioSystem.getClip();
             clip.open(stream);
             clip.start();
             
         } catch (LineUnavailableException ex) {
             Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
         }
     } catch (UnsupportedAudioFileException ex) {
         Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
     } catch (IOException ex) {
         Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
     }
}
void lost(){
    
     try {
         AudioInputStream stream=AudioSystem.getAudioInputStream(new File("not.wav"));
         try {
             Clip clip=AudioSystem.getClip();
             clip.open(stream);
             clip.start();
         } catch (LineUnavailableException ex) {
             Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
         }
     } catch (UnsupportedAudioFileException ex) {
         Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
     } catch (IOException ex) {
         Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
     }
}
    private void AActionPerformed(java.awt.event.ActionEvent evt) {                                  
    dogru.setText("");
    mesaj.setText("");
        if(answers.get(i).equals(A.getText())){
     // dogru.setText("DOGRU!");
            ekle();
   
      
     i++;
      if(i==1){
        bir.setForeground(Color.yellow);   
      }
      if(i==2){
        iki.setForeground(Color.yellow);   
      }
       if(i==3){
        uc.setForeground(Color.yellow);   
      }
        if(i==4){
        dort.setForeground(Color.yellow);   
      }
         if(i==5){
       bes.setForeground(Color.yellow);   
      }
           if(i==6){
       alti.setForeground(Color.yellow);   
      }
         if(i==7){
       yedi.setForeground(Color.yellow);
       JOptionPane.showMessageDialog(this,"Tebrikler 30.0000 TL lik büyük ödülü kazandınız");
            System.exit(0);
      }
   
        }
      else{
          mesaj.setText("YANLIS!");
          lost();
            JOptionPane.showMessageDialog(this,"Malesef yarışmadan elendiniz");
            System.exit(0);
           
      }
     
    
         al();
     
    }                                 

    private void BActionPerformed(java.awt.event.ActionEvent evt) {                                  
   dogru.setText("");
    mesaj.setText("");
        if(answers.get(i).equals(B.getText())){
      //dogru.setText("DOGRU!");
      ekle();
      i++;
     if(i==1){
        bir.setForeground(Color.yellow);   
      }
      if(i==2){
        iki.setForeground(Color.yellow);   
      }
       if(i==3){
        uc.setForeground(Color.yellow);   
      }
        if(i==4){
        dort.setForeground(Color.yellow);   
      }
         if(i==5){
       bes.setForeground(Color.yellow);   
      }
           if(i==6){
       alti.setForeground(Color.yellow);   
      }
         if(i==7){
       yedi.setForeground(Color.yellow);   
         JOptionPane.showMessageDialog(this,"Tebrikler 30.0000 TL lik büyük ödülü kazandınız");
            System.exit(0);
      }
   
        }
      else{
          mesaj.setText("YANLIS!");
          lost();
              JOptionPane.showMessageDialog(this,"Malesef yarışmadan elendiniz");
            System.exit(0);
      }
    
    
         al();
     
    }                                 

    private void CActionPerformed(java.awt.event.ActionEvent evt) {                                  
     
        // dogru.setText("");
  //  mesaj.setText("");
    if(answers.get(i).equals(C.getText())){
   //   dogru.setText("DOGRU!");
      ekle();
      i++;
     if(i==1){
        bir.setForeground(Color.yellow);   
      }
      if(i==2){
        iki.setForeground(Color.yellow);   
      }
       if(i==3){
        uc.setForeground(Color.yellow);   
      }
        if(i==4){
        dort.setForeground(Color.yellow);   
      }
         if(i==5){
       bes.setForeground(Color.yellow);   
      }
           if(i==6){
       alti.setForeground(Color.yellow);   
      }
         if(i==7){
       yedi.setForeground(Color.yellow);   
         JOptionPane.showMessageDialog(this,"Tebrikler 30.0000 TL lik büyük ödülü kazandınız");
            System.exit(0);
      }
   
    }
    
      else{
          mesaj.setText("YANLIS!");
          lost();
              JOptionPane.showMessageDialog(this,"Malesef yarışmadan elendiniz");
      System.exit(0);
      }
      
     
         al();
     
    }                                 

    private void DActionPerformed(java.awt.event.ActionEvent evt) {                                  
       //dogru.setText("");
    mesaj.setText("");
        if(answers.get(i).equals(D.getText())){
  //   dogru.setText("DOGRU!");
      ekle();
      i++;
     if(i==1){
        bir.setForeground(Color.yellow);   
      }
      if(i==2){
        iki.setForeground(Color.yellow);   
      }
       if(i==3){
        uc.setForeground(Color.yellow);   
      }
        if(i==4){
        dort.setForeground(Color.yellow);   
      }
         if(i==5){
       bes.setForeground(Color.yellow);   
      }
           if(i==6){
       alti.setForeground(Color.yellow);   
      }
         if(i==7){
       yedi.setForeground(Color.yellow);   
         JOptionPane.showMessageDialog(this,"Tebrikler 30.0000 TL lik büyük ödülü kazandınız");
            System.exit(0);
      }
   
    
        }
      else{
          mesaj.setText("YANLIS!");
            lost();
              JOptionPane.showMessageDialog(this,"Malesef yarışmadan elendiniz");
         System.exit(0);
      }
    
     
         al();
    
    }                                 

    private void yariActionPerformed(java.awt.event.ActionEvent evt) {                                     
 String cevap=answers.get(i);
   int j=0;
   String c1=A.getText();
    String c2=B.getText();
     String c3=C.getText();
      String c4=D.getText();
      if(!(c1.equals(cevap))){
         A.setText("");
         j++;
      }
      if(!(c2.equals(cevap))){
          B.setText("");
          j++;
      }
      if((!(c3.equals(cevap)))&& j!=2){
          C.setText("");
          j++;
      }
       if((!(c4.equals(cevap)))&& j!=2){
          D.setText("");
          j++;
      }  
       // TODO add your handling code here:
    }                                    

    private void joker1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
     String cevap=answers.get(i);
   int j=0;
   boolean n=false;
   String c1=A.getText();
    String c2=B.getText();
     String c3=C.getText();
      String c4=D.getText();
      if(!(c1.equals(cevap))){
         A.setText("");
         j++;
      }
      if(!(c2.equals(cevap))){
          B.setText("");
          j++;
      }
      if((!(c3.equals(cevap)))&& j!=2){
          C.setText("");
          j++;
      }
       if((!(c4.equals(cevap)))&& j!=2){
          D.setText("");
          j++;
          
      }  
       joker1.show(false);
    }                                      

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
     Seyirci seyirci =new Seyirci();
     jButton1.show(false);
    
     String c1=A.getText();
    String c2=B.getText();
     String c3=C.getText();
      String c4=D.getText();
      String cevap=answers.get(i);
      if(c1.equals(cevap)){
         seyirci.setVisible(true);
         seyirci.yap("A");
      }
     else if(c2.equals(cevap)){
       
           seyirci.setVisible(true);
         seyirci.yap("B");
      }
    else if(c3.equals(cevap)){
        
          seyirci.setVisible(true);
         seyirci.yap("C");
      }
      else{
        seyirci.setVisible(true);
         seyirci.yap("D");
         
          
      }  
             
    }                                        

    private void cekilActionPerformed(java.awt.event.ActionEvent evt) {                                      
         
             if (i==2){
                 JOptionPane.showMessageDialog(this,"Tebrikle 2.000 TL kazandınız");
                 System.exit(0);
             }
              if (i==3){
                 JOptionPane.showMessageDialog(this,"Tebrikle 3.000 TL kazandınız");
                 System.exit(0);
             }
                if (i==4){
                 JOptionPane.showMessageDialog(this,"Tebrikle 7.500 TL kazandınız");
                 System.exit(0);
             }
                   if (i==5){
                 JOptionPane.showMessageDialog(this,"Tebrikle 15.000 TL kazandınız");
                 System.exit(0);
             }
       
    }                                     
 public void al() {
   
 
     
    soru.setText(queue.poll());
    A.setText(a.poll());
      B.setText(b.poll());
        C.setText(c.poll()); 
        D.setText(d.poll());
        if(i==0){
          cekil.show(false);
        }
         if (i==1){
           cekil.show(false);
           
        }
          if (i==2){
           cekil.show(true);
        }
           if (i==3){
           cekil.show(true);
        }
        if (i==4){
           cekil.show(true);
        }
         if (i==5){
            cekil.show(true);
        }
         if (i==6){
            cekil.show(false);
        }
     
      
        
        /*  while(j>0){
         

 Thread.sleep(1000);
 time.setText(String.valueOf(j));
 j--;
        }  
   */
   
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JButton C;
    private javax.swing.JButton D;
    private javax.swing.JLabel alti;
    private javax.swing.JLabel bes;
    private javax.swing.JLabel bir;
    private javax.swing.JButton cekil;
    private javax.swing.JLabel dogru;
    private javax.swing.JLabel dort;
    private javax.swing.JLabel iki;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton joker1;
    private javax.swing.JLabel mesaj;
    private javax.swing.JLabel soru;
    private javax.swing.JLabel uc;
    private javax.swing.JLabel yedi;
    // End of variables declaration                   
}
